// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhkfyopvxgoyvpuqkajg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoa2Z5b3B2eGdveXZwdXFrYWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjQ2NzYsImV4cCI6MjA3MzEwMDY3Nn0.58KkcLfgSX7-YPM-w4AGWzMswyPvJ_mkeVejoyGhqqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});